### ISSUE TITLE
Cant copy a tree in my save file

### ISSUE THREAD

**Issue by HarryGWA** [jaquadro/NBTExplorer#107]
Im trying to change my player data in the level.dat folder to my player data from the playerdata folder from a realms save my friend downloaded but the playerdata .dat labled 5a084939-e1b0-4f18-af8f-99ffec89b401.dat that I've identified as mine cant be copied entirely and has a wooden crate icon instead of the carboard box one. Was just wondering if there is anything that i can do to be able to copy the file in its entirety. 
![Capture](https://user-images.githubusercontent.com/73405374/97092939-df4c4380-163f-11eb-89ae-30e5a6393617.PNG)

**Comment by HarryGWA** [comment]
I figured out that the file is a full .dat file and that im going to have to copy each aspect over to the level.dat

**Comment by rc6ty** [comment]
I'd like to reopen the issue, becouse while there is a workaround, I think that this is a common enough use for NBTExplrer that there should be a cleaner/easier way of coping whole .dat files into other ones.
