### ISSUE TITLE
Why can't the Find function find this string?

### ISSUE THREAD

**Issue by shimajima** [jaquadro/NBTExplorer#133]
See screenshots. I am using NBTExplorer's "Find" function to search for a string and it can't find it for some reason. Would love any feedback you have!

![image](https://user-images.githubusercontent.com/61395186/185769142-5e1bedd0-7bd0-4995-bde1-f6500e9c47d5.png)

![image](https://user-images.githubusercontent.com/61395186/185769161-6351ddd5-312b-4b32-9f92-6cc8ab0afcec.png)

![image](https://user-images.githubusercontent.com/61395186/185769188-d2c2e03e-8428-4229-b3c3-fb9ac08df090.png)

![image](https://user-images.githubusercontent.com/61395186/185769206-a3e52b5f-d2c6-4091-b7e2-821c840bbe9d.png)

![image](https://user-images.githubusercontent.com/61395186/185769229-c88ff638-f641-4de4-bb81-8c1f14f4e461.png)

**Comment by shimajima** [comment]
Hello folks, please ignore this issue. I have switched to tryashtar's NBT Studio (the spiritual successor to NBTExplorer) and the find/replace function works great. Thanks.

**Comment by Try-H4ck-M3** [comment]
Any sollution?

**Comment by RealRTTV** [comment]
switch editors
