### ISSUE TITLE
Change Tag Sort order

### ISSUE THREAD

**Issue by codewarrior0** [jaquadro/NBTExplorer#24]
Tags are currently ordered by the numeric ID of the tag.

I propose a new sorting order, which I'm not ashamed to say is the one I use in MCEdit 2.0:

- Compounds
- Lists
- All non-array types, ordered by tag name
- Array types

This will put collection types first, which makes it easier to drill down into nested collections (e.g. level.dat/Data/Player). Plain data types are grouped together, ignoring the exact data type, making it easier to find a tag by name. Arrays are infrequently edited and are listed last.

If you know offhand which .NET classes are responsible for tree views and sort ordering, any implementation tips would be appreciated. I might use it as an excuse to get into .NET development.

**Comment by d-kr** [comment]
https://msdn.microsoft.com/en-us/library/system.windows.forms.treeview.treeviewnodesorter.aspx

Implement your own IComparer. See the example.

**Comment by codewarrior0** [comment]
Thanks! That was fun.

**Comment by jaquadro** [comment]
I agree, that looks like a more useful sort order.  Thanks for the implementation.

I changed the string compares to natural compares (had to pull in a little third party code), so numbers will sort in a human-friendly manner.  Should make a marked difference on the region and chunk listings.

**Comment by codewarrior0** [comment]
Great! One last thing... the NaturalComparer doesn't respect negative numbers. I'll push a fix shortly.
