### ISSUE TITLE
Allow opening NBT files with any file extension

### ISSUE THREAD

**Issue by codewarrior0** [jaquadro/NBTExplorer#31]
Buildcraft's 'blueprints' are stored as `*.bpt` files, but are otherwise ordinary gzip-compressed NBT files. NBTExplorer fails to open these files unless they are renamed to `*.nbt` or `*.dat`. Similarly, the mod Recurrent Complex has its own export format stored as `*.rc` files that are also gzip-compressed NBT files. I have the feeling that there are other mods that store NBT files with an extension other than `*.dat`

~~Instead of adding these file extensions to NbtFileDataNode.SupportedNamePattern, a more general solution would be to change that pattern to match any file, and then add NbtFileDataNode to the filetype registry last, so it catches any types not matched by the other file nodes. I'm not sure how DirectoryDataNode would have to change to accommodate that, though.~~

This would also address #21.

**Comment by jaquadro** [comment]
The main purpose of the filter was to avoid trying to load and parse (and fail) on every file in a given directory tree.  My assumption is it would be slow and thrashy to do that.  But I haven't tried or benchmarked it.  Do you have any data points on this kind of thing?

**Comment by codewarrior0** [comment]
Nope. It would be fine if the directory view stays like it is. What I'm really asking for is to skip the filename match when a single file is opened directly.

It would also be cool to have a Right Click -> Expand as NBT option for the directory view.

**Comment by codewarrior0** [comment]
I'd expect the NBT parser to fail fast, since the first byte always has to be 0x0A and not many text files start with a LF. But I'd need benchmarks to be sure. Here's one data point, though. I walked my entire saves folder (8 saves) for an instance with about 80 mods, and found out how many files aren't matched by any of the name patterns.

Out of 930 files, only 120 do not end in either .mcr, .mca, or .dat.

**Comment by LB--** [comment]
I support this idea - I don't understand how it could negatively affect the existing behavior given the above constraints.

**Comment by Walkman100** [comment]
> Nope. It would be fine if the directory view stays like it is. What I'm really asking for is to skip the filename match for NBT files when a single file is opened directly.

:+1:

**Comment by jaquadro** [comment]
yeah, I don't see any problem with doing that.  But I will at least want to see how the directory view responds.

**Comment by codewarrior0** [comment]
I figured out how to do it without touching the directory view. Let me know what you think.
