### ISSUE TITLE
Transfer data from one NBT file to another

### ISSUE THREAD

**Issue by Pocketkid2** [jaquadro/NBTExplorer#38]
I would really like to see a feature like this, for example copying just an inventory from one NBT player data file to another without having to do it manually

**Comment by jaquadro** [comment]
Can you clarify further?  You can already copy and paste a tree of items, and it persists on the clipboard so you could copy between two files or two instances of the program.

Are you looking for a command line capability in NBTUtil?

**Comment by Pocketkid2** [comment]
Really? Because when I had two instances of NBTExplorer open and I copied stuff it wouldn't paste on the other window.

I am using windows 10

**Comment by jaquadro** [comment]
Yes, I tested it on Windows 10 just before writing that.  Maybe try copying some different things -- do all of them not work?

**Comment by LB--** [comment]
Make sure you have a compound tag selected before trying to paste?

**Comment by Pocketkid2** [comment]
Hmm maybe I wasn't doing it right. I think it works now.
