### ISSUE TITLE
Bug with long lengths

### ISSUE THREAD

**Issue by MeepMu** [jaquadro/NBTExplorer#41]
longs can be 9 bytes (72 bits) long, Notch specified 8 bytes () only in his specification at: http://web.archive.org/web/20110723210920/http://www.minecraft.net/docs/NBT.txt

**Comment by jaquadro** [comment]
Where are you getting 9 bytes from?

**Comment by MeepMu** [comment]
![nbtexplorer_bug](https://cloud.githubusercontent.com/assets/15966053/11916950/0005c688-a6f0-11e5-8c0d-fac449086547.jpg)
Unless my understanding of bytes is wrong, that should be a bug.

**Comment by jaquadro** [comment]
Your understanding of bytes is incorrect.

64-bit (long) integers have a decimal range of  −9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.  Up to 19 digits in a text field.  If it were converted to hex, it would take up 16 digits in a text field, which is maybe what you were expecting.

It's being handled correctly; there is no bug here.

**Comment by MeepMu** [comment]
Ah, yeah sorry, i did actiually know that, i dont know what i was thinking. Really usefull program btw. :)
