### ISSUE TITLE
How do I install this on mac?

### ISSUE THREAD

**Issue by iriksor** [jaquadro/NBTExplorer#91]
The title is self-explanatory. Thanks for any help given!

**Comment by shai** [comment]
It really depends (AFAIK) on which MAC you own (what version of MacOS you have installed). Have you read #83?

**Comment by shai** [comment]
Also, I found this today, might be a good alternative: [webNBT](https://irath96.github.io/webNBT/)

**Comment by iriksor** [comment]
> Also, I found this today, might be a good alternative: [webNBT](https://irath96.github.io/webNBT/)

Thanks for your help, I think I'll just use webNBT, I tried to install it for a while (I'm still on Mojave) but to no avail. Thank you for your help.
